name: Machine Learning Workflow CI

# Trigger: Berjalan setiap kali ada push ke branch main atau dijalankan manual
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repositori
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 3. Install MLflow dan dependencies pendukung
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow dagshub scikit-learn pandas numpy matplotlib seaborn

    # 4. Jalankan Re-training Model dengan menyuntikkan environment token DagsHub
    - name: Run MLflow Project Re-training
      env:
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        mlflow run MLProject/ --entry-point main --env-manager local

    # 5. Login ke Docker Hub secara aman menggunakan GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 6. Build & Push Docker Image menggunakan perintah mlflow build-docker
    - name: Build and Push Docker Image
      run: |
        mlflow models build-docker -m "runs:/latest/model" -n "${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-model:latest" --enable-mlserver
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/predictive-maintenance-model:latest